build: kivymd >= 2.0.0 does not exist
When installing Kv-developer through Git clone:
pip install -e .

Obtaining file:///home/user-name/Testing/Kiv/KvDeveloper
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting kivy>=2.0.0
  Using cached Kivy-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.0 MB)
ERROR: Could not find a version that satisfies the requirement kivymd>=2.0.0 (from kvdeveloper) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.100.2, 0.102.0, 0.102.1, 0.103.0, 0.104.0, 0.104.1, 0.104.2, 1.0.1, 1.0.2, 1.1.1, 1.2.0)
ERROR: No matching distribution found for kivymd>=2.0.0